### ISSUE TITLE
Ask HZ to release podcast logo under CC license

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/Zimmerman-en-Space-podcast#4]
Ask HZ to release podcast logo under CC license

**Comment by hz37** [comment]
![zes](https://github.com/user-attachments/assets/cf1d899c-24ea-42ed-8a3d-f1cdc1b250c2)
![zes](https://github.com/user-attachments/assets/f8c17ca4-c503-49ca-8376-4f9f36ebf72a)
![zes liggend](https://github.com/user-attachments/assets/a54316e6-aa87-4e97-a0f6-5c6ccfa81924)


CC0: This work has been marked as dedicated to the public domain.

**Comment by ookgezellig** [comment]
Super, thanks! I'll add them to [https://commons.wikimedia.org/wiki/Category:Zimmerman_en_Space_podcast](https://commons.wikimedia.org/wiki/Category:Zimmerman_en_Space_podcast) and [https://www.wikidata.org/wiki/Q130355362](https://www.wikidata.org/wiki/Q130355362).

**Comment by ookgezellig** [comment]
Backup of this page in Waycak Machine: https://web.archive.org/web/20240928113725/https://github.com/ookgezellig/Zimmerman-en-Space-podcast/issues/4
