### ISSUE TITLE
Ask HZ for portrait photo under CC license

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/Zimmerman-en-Space-podcast#5]
Ask HZ for portrait photo under CC license

**Comment by hz37** [comment]
![cables_202269_174423](https://github.com/user-attachments/assets/11e8270c-6a12-47fa-a1db-ad3d1a37fcfe)

![Paleis op de Dam Andre Kuipers avond 7 juni 2023](https://github.com/user-attachments/assets/d9337898-7414-46f3-a1ee-86dc7c11899f)

CC0: This work has been marked as dedicated to the public domain.

**Comment by ookgezellig** [comment]
Super, thanks! I'll add them to https://commons.wikimedia.org/wiki/Category:Zimmerman_en_Space_podcast and https://www.wikidata.org/wiki/Q130279350

**Comment by ookgezellig** [comment]
Backup of this page in Wayback Machine: https://web.archive.org/web/20240928112539/https://github.com/ookgezellig/Zimmerman-en-Space-podcast/issues/5
