### ISSUE TITLE
Clearify copyright status of Zimmerman in Space podcast episodes

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/Zimmerman-en-Space-podcast#8]
Clearify copyright status of Zimmerman *in* Space podcast episodes.

Maybe also CC0?

**Comment by hz37** [comment]
Unfortunately, this is not possible. The NPO is copyright holder of the episodes. Also, just about every episode of Zimmerman _in_ Space contains copyrighted music.

**Comment by ookgezellig** [comment]
Ok, that is a pitty. I'll close this issue for now.
